Fix pom.xml (added necessary dependency).
Fix runtime error.
---
$ java -cp blockchain-client.jar org.app.network.CreateChannel
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Apr 07, 2019 7:33:50 PM org.app.util.Util deleteDirectory
INFO: Deleting - users
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.app.util.Util.getEnrollment(Util.java:132)
	at org.app.network.CreateChannel.main(CreateChannel.java:50)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 2 more
---